//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rizemetroturizmDemo.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus
    {
        public int busId { get; set; }
        public string number { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public int modelYear { get; set; }
        public string color { get; set; }
        public int numberofSeats { get; set; }
        public int personel1 { get; set; }
        public int personel2 { get; set; }
        public int personel3 { get; set; }
        public int personel4 { get; set; }
        public bool busStatus { get; set; }
        public string busImage1 { get; set; }
        public string busImage2 { get; set; }
    
        public virtual personal personal { get; set; }
        public virtual personal personal1 { get; set; }
        public virtual personal personal2 { get; set; }
        public virtual personal personal3 { get; set; }
    }
}
