//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rizemetroturizmDemo.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class expeditions
    {
        public int expeditionId { get; set; }
        public int depature { get; set; }
        public int destination { get; set; }
        public int bus { get; set; }
        public Nullable<int> restArea { get; set; }
        public Nullable<bool> expeditionStatus { get; set; }
    
        public virtual city city { get; set; }
        public virtual city city1 { get; set; }
        public virtual restArea restArea1 { get; set; }
    }
}
