//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rizemetroturizmDemo.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class metroturizmDBEntities : DbContext
    {
        public metroturizmDBEntities()
            : base("name=metroturizmDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bus> bus { get; set; }
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<departments> departments { get; set; }
        public virtual DbSet<expeditions> expeditions { get; set; }
        public virtual DbSet<personal> personal { get; set; }
        public virtual DbSet<restArea> restArea { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
