//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rizeMetroTurizmMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus
    {
        public int busId { get; set; }
        public string busNumber { get; set; }
        public string busBrand { get; set; }
        public string busModel { get; set; }
        public Nullable<int> busYear { get; set; }
        public Nullable<int> busNumberOfSeats { get; set; }
        public Nullable<int> busPersonal1 { get; set; }
        public string busImage { get; set; }
    
        public virtual person person { get; set; }
    }
}
