//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rizeMetroTurizmMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class expedition
    {
        public int expeditionId { get; set; }
        public string expeditionNumber { get; set; }
        public Nullable<int> depature { get; set; }
        public Nullable<int> destination { get; set; }
    
        public virtual city city { get; set; }
        public virtual city city1 { get; set; }
    }
}
